### ISSUE TITLE
Assets Controller

### ISSUE THREAD

**Issue by davetgreen** [davetgreen/wp-plugin-skeleton#15]
Need to rethink the naming convention for the class that enqueues the assets; is this a true controller?

It exists solely to enqueue our CSS and JS, but it's not taking any input in from any routes! For all intents and purposes it's nearly identical to some of the other classes. I guess the context *does* change in terms of we have public, admin and customizer assets, but does this justify calling it a controller?

Penny for @mwtsn thoughts on this, as it continues to bug me. 🤔

**Comment by mwtsn** [comment]
@davetgreen `class-enqueue-assets.php`

**Comment by davetgreen** [comment]
@mwtsn I had a feeling you'd concur on this, cheers!
